"""empty message

Revision ID: 2743c73a5a1f
Revises: d484bcbc474e
Create Date: 2022-05-16 01:15:53.707628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2743c73a5a1f'
down_revision = 'd484bcbc474e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'date')
    # ### end Alembic commands ###
