"""empty message

Revision ID: 76c4fcaf24d2
Revises: 68d99e447b95
Create Date: 2022-05-15 22:55:57.485891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c4fcaf24d2'
down_revision = '68d99e447b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('image_file', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
